name: Security Audit

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install Dependencies
        run: poetry install

      - name: Run Supply Chain Audit
        run: poetry run pip-audit
